# Generated by Django 2.0.7 on 2018-08-02 19:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, choices=[('p', 'PCR'), ('n', 'NGS'), ('d', 'Desconocido')], default='n', help_text='Método usado', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, choices=[('p', 'Positivo'), ('n', 'Negativo'), ('i', 'No concluyente'), ('d', 'Desconocido')], default='n', help_text='Estado del resultado', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectId', models.CharField(help_text='(8 dígitos)', max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('\\d{8,8}', 'Ingresar 8 digitos')])),
            ],
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(blank=True, choices=[('s', 'Si'), ('n', 'No'), ('d', 'Desconocido')], default='n', help_text='Estado del testing', max_length=1)),
                ('subjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crf.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='testing',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crf.Variation'),
        ),
        migrations.AddField(
            model_name='testing',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='result',
            name='testing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crf.Testing'),
        ),
        migrations.AddField(
            model_name='method',
            name='testing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crf.Testing'),
        ),
    ]
